# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'output_hdf5.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(790, 307)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.vdo_browse_btn = QtGui.QPushButton(Dialog)
        self.vdo_browse_btn.setObjectName(_fromUtf8("vdo_browse_btn"))
        self.gridLayout.addWidget(self.vdo_browse_btn, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.save_browse_btn = QtGui.QPushButton(Dialog)
        self.save_browse_btn.setObjectName(_fromUtf8("save_browse_btn"))
        self.gridLayout.addWidget(self.save_browse_btn, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.save_path = QtGui.QLineEdit(Dialog)
        self.save_path.setObjectName(_fromUtf8("save_path"))
        self.gridLayout.addWidget(self.save_path, 1, 1, 1, 1)
        self.vdo_path = QtGui.QLineEdit(Dialog)
        self.vdo_path.setObjectName(_fromUtf8("vdo_path"))
        self.gridLayout.addWidget(self.vdo_path, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_2.addWidget(self.progressBar, 3, 0, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.pano_tab = QtGui.QWidget()
        self.pano_tab.setObjectName(_fromUtf8("pano_tab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.pano_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 41))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_c51 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_c51.setObjectName(_fromUtf8("checkBox_c51"))
        self.gridLayout_3.addWidget(self.checkBox_c51, 1, 2, 1, 1)
        self.checkBox_c50 = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_c50.setObjectName(_fromUtf8("checkBox_c50"))
        self.gridLayout_3.addWidget(self.checkBox_c50, 1, 1, 1, 1)
        self.checkBox_pano_cam = QtGui.QCheckBox(self.gridLayoutWidget_2)
        self.checkBox_pano_cam.setObjectName(_fromUtf8("checkBox_pano_cam"))
        self.gridLayout_3.addWidget(self.checkBox_pano_cam, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pano_tab, _fromUtf8(""))
        self.line_tab = QtGui.QWidget()
        self.line_tab.setObjectName(_fromUtf8("line_tab"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.line_tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 391, 41))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.checkBox_61 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_61.setObjectName(_fromUtf8("checkBox_61"))
        self.gridLayout_4.addWidget(self.checkBox_61, 1, 2, 1, 1)
        self.checkBox_64 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_64.setObjectName(_fromUtf8("checkBox_64"))
        self.gridLayout_4.addWidget(self.checkBox_64, 1, 4, 1, 1)
        self.checkBox_65 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_65.setObjectName(_fromUtf8("checkBox_65"))
        self.gridLayout_4.addWidget(self.checkBox_65, 1, 5, 1, 1)
        self.checkBox_cam_6 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_cam_6.setObjectName(_fromUtf8("checkBox_cam_6"))
        self.gridLayout_4.addWidget(self.checkBox_cam_6, 1, 0, 1, 1)
        self.checkBox_60 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_60.setObjectName(_fromUtf8("checkBox_60"))
        self.gridLayout_4.addWidget(self.checkBox_60, 1, 1, 1, 1)
        self.checkBox_62 = QtGui.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_62.setObjectName(_fromUtf8("checkBox_62"))
        self.gridLayout_4.addWidget(self.checkBox_62, 1, 3, 1, 1)
        self.gridLayoutWidget_4 = QtGui.QWidget(self.line_tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 391, 41))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.checkBox_74 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_74.setObjectName(_fromUtf8("checkBox_74"))
        self.gridLayout_5.addWidget(self.checkBox_74, 1, 4, 1, 1)
        self.checkBox_70 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_70.setObjectName(_fromUtf8("checkBox_70"))
        self.gridLayout_5.addWidget(self.checkBox_70, 1, 1, 1, 1)
        self.checkBox_71 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_71.setObjectName(_fromUtf8("checkBox_71"))
        self.gridLayout_5.addWidget(self.checkBox_71, 1, 2, 1, 1)
        self.checkBox_75 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_75.setObjectName(_fromUtf8("checkBox_75"))
        self.gridLayout_5.addWidget(self.checkBox_75, 1, 5, 1, 1)
        self.checkBox_cam_7 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_cam_7.setObjectName(_fromUtf8("checkBox_cam_7"))
        self.gridLayout_5.addWidget(self.checkBox_cam_7, 1, 0, 1, 1)
        self.checkBox_72 = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.checkBox_72.setObjectName(_fromUtf8("checkBox_72"))
        self.gridLayout_5.addWidget(self.checkBox_72, 1, 3, 1, 1)
        self.tabWidget.addTab(self.line_tab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.out_h5_btn = QtGui.QPushButton(Dialog)
        self.out_h5_btn.setObjectName(_fromUtf8("out_h5_btn"))
        self.horizontalLayout.addWidget(self.out_h5_btn)
        self.stop_btn = QtGui.QPushButton(Dialog)
        self.stop_btn.setObjectName(_fromUtf8("stop_btn"))
        self.horizontalLayout.addWidget(self.stop_btn)
        self.cancel_btn = QtGui.QPushButton(Dialog)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBox_pano_cam, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_c50.setChecked)
        QtCore.QObject.connect(self.checkBox_pano_cam, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_c51.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_60.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_61.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_64.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_65.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_70.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_71.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_74.setChecked)
        QtCore.QObject.connect(self.checkBox_cam_7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.checkBox_75.setChecked)
        QtCore.QObject.connect(self.cancel_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "OUTPUT HDF5", None))
        self.vdo_browse_btn.setText(_translate("Dialog", "Browse...", None))
        self.label_2.setText(_translate("Dialog", "VDO Path:", None))
        self.save_browse_btn.setText(_translate("Dialog", "Browse...", None))
        self.label_3.setText(_translate("Dialog", "Save Path:", None))
        self.checkBox_c51.setText(_translate("Dialog", "c51", None))
        self.checkBox_c50.setText(_translate("Dialog", "c50", None))
        self.checkBox_pano_cam.setText(_translate("Dialog", "pano_cam", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pano_tab), _translate("Dialog", "PANO_CAM", None))
        self.checkBox_61.setText(_translate("Dialog", "61", None))
        self.checkBox_64.setText(_translate("Dialog", "64", None))
        self.checkBox_65.setText(_translate("Dialog", "65", None))
        self.checkBox_cam_6.setText(_translate("Dialog", "cam_6", None))
        self.checkBox_60.setText(_translate("Dialog", "60", None))
        self.checkBox_62.setText(_translate("Dialog", "62", None))
        self.checkBox_74.setText(_translate("Dialog", "74", None))
        self.checkBox_70.setText(_translate("Dialog", "70", None))
        self.checkBox_71.setText(_translate("Dialog", "71", None))
        self.checkBox_75.setText(_translate("Dialog", "75", None))
        self.checkBox_cam_7.setText(_translate("Dialog", "cam_7", None))
        self.checkBox_72.setText(_translate("Dialog", "72", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.line_tab), _translate("Dialog", "LINE_CAM", None))
        self.out_h5_btn.setText(_translate("Dialog", "Output HDF5", None))
        self.stop_btn.setText(_translate("Dialog", "Stop", None))
        self.cancel_btn.setText(_translate("Dialog", "Cancel", None))

